version: 2

node: &node
  working_directory: ~/project
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2

jobs:
  install_dependencies:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-
            - v1-npm-deps-
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - run:
          name: Yarn Install
          command: |
            echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
            yarn install --non-interactive --no-lockfile --verbose
      - run:
          name: Set node_modules bin path
          command: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}
          paths:
            - ../.cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    <<: *node
    parallelism: 6
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test ember-lts-2.12
          command: |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-lts-2.12 --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-lts-2.16 --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-lts-2.18 --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-release --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-beta --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-canary --skip-cleanup=true
      - run:
          name: Run Tests
          command:  |
            echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
            ember try:one ember-default --skip-cleanup=true

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies:
          context: org-global
      - tests:
          context: org-global
          requires:
            - install_dependencies
