version: 2

node: &node
  working_directory: ~/project
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2

jobs:
  install_dependencies:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-
            - v1-npm-deps-
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - run:
          name: Yarn Install
          command: |
            echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
            yarn install --non-interactive --no-lockfile --verbose
      - run:
          name: Set node_modules bin path
          command: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Ember Tests
          command: ember test
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}
          paths:
            - ../.cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  ember-lts-2.12:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-lts-2.12 --skip-cleanup=true

  ember-lts-2.16:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-lts-2.16 --skip-cleanup=true

  ember-lts-2.18:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-lts-2.18 --skip-cleanup=true

  ember-release:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-release --skip-cleanup=true

  ember-beta:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-beta --skip-cleanup=true

  ember-canary:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-canary --skip-cleanup=true

  ember-default:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-default --skip-cleanup=true

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies:
          context: org-global
      - ember-lts-2.12:
          context: org-global
          requires:
            - install_dependencies
      - ember-lts-2.16:
          context: org-global
          requires:
            - install_dependencies
      - ember-lts-2.18:
          context: org-global
          requires:
            - install_dependencies
      - ember-release:
          context: org-global
          requires:
            - install_dependencies
      - ember-beta:
          context: org-global
          requires:
            - install_dependencies
      - ember-canary:
          context: org-global
          requires:
            - install_dependencies
      - ember-default:
          context: org-global
          requires:
            - install_dependencies
